# Generated by Django 4.0.4 on 2022-05-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='description',
            new_name='item',
        ),
    ]
