# Generated by Django 4.0.4 on 2022-05-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Inventories'},
        ),
    ]
